# Project-wide Gradle settings.

# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE will override
# any settings specified in this file.

# Specifies the JVM arguments used for the Gradle daemon process.
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -Djava.net.preferIPv4Stack=true

# AndroidX support
android.useAndroidX=true

# Specifies which CPU architectures to build.
reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64

# Enable React Native New Architecture.
newArchEnabled=true

# Enable Hermes JavaScript engine.
hermesEnabled=true

# Enable edge-to-edge display support.
edgeToEdgeEnabled=true

